- name: Search for Next Available IP
  hosts: all
  connection: local
  gather_facts: false
  
  vars:
    nios_provider:
      host: 192.168.1.190
      username: admin
      password: infoblox

  tasks:
       
    - name: Return next available IP addresses for network excluding gateway IPs
      set_fact:
        ipaddr: "{{ lookup('nios_next_ip', 192.168.10.0/24, provider=nios_provider) }}"

    - name: Print next available IP
      debug:
        var: ipaddr

   # - name: Save information of next available IP for subsequent workflow
   #   set_stats:
   #     data:
   #       ipv4_address: "{{ ipaddr }}"
