- name: Search for Next Available IP
  hosts: all
  connection: local
  gather_facts: false
  
  tasks:
  
    - name: Return next available IP addresses for network "{{ ipam_network }}", excluding gateway IPs
      ansible.builtin.set_fact:
        ipaddr: "{{ lookup('community.general.nios_next_ip', '192.168.20.0/24', provider={'host': '192.168.1.190', 'username': 'admin', 'password': 'infoblox'}) }}"
 
    - name: Print next available IP
      debug:
      var: ipaddr
 
    - name: Save information of next available IP for subsequent workflow
      set_stats:
      data:
        ipv4_address: "{{ ipaddr }}"
